# 手写Promise

JS异步编程的一种解决方案

注意下面手写的代码只是为了训练我们编码能力，不能用于生产环境

## 基本的测试用例

```javascript
// 使用方式如下：
new Promise((resolve,reject)=>{
	// 1.同步方式使用
	// resolve() // 或者 reject('抛出错误')
	// 2.异步方式使用（常用）
	setTimeout(()=>{
	  if(res.code === 200){
		resolve(data)
	  }else{
		reject(res.msg)
	  }
	},2000)
}).then((data)=>{ // Promise实例调用.then方法
	console.log(data)
},(reason)=>{
	console.log(reason)
}}).catch((reason)=>{
	console.log(reason)
})
```

自定义promise

## 第一步：回忆使用方法，写出主函数

```javascript
/** 第一步，回忆使用方法，写出主函数
  1.他是一个类
  2.他接收一个回调函数作为参数
  3.回调函数会自动接收到2个实参函数
  4.可以往实参函数里面传参数
  代码实现如下：
*/
class self_promise {
	constructor(excutor){

	}
	function resolve(data){

	}
	function reject(reason){

	}
	excutor(resolve,reject)
}
```

## 第二步：根据具体实现，完善代码主函数的实现细节

```javascript
 /** 第二步，根据具体实现，完善代码主函数的实现细节
  1.调用resolve或者reject后，会有2个直接改变：1）参数作为数据保存到实例中（后续会在.then()或者.catch()中用到） 2）状态改变，起始状态为pending，调用resolve后变为fulfilled，调用reject后变为rejected
  2.因此，Promise实例自身需要维护2个数据 1）结果  2）当前状态（默认为pending），在调用resolve或者reject函数时改变自身维护的这两个值
  3.另外，需要注意的是，状态只能改变一次。多次调用resolve或者reject，以第一次调用为准。这里的实现是通过判断state是否是pending确定的。
 */
class self_promise {
	constructor(excutor){
		// const self = this  // 保存this，因为作为参数的回调函数调用后this会指向window；也可以使用箭头函数去避免这个问题。
		this.data = null
		this.state = 'pending'
		const resolve = (data)=>{
			if(this.state !== 'pending') return 
			this.data = data
			this.state = 'fulfilled'
		}
		const reject = (data)=>{
			if(this.state !== 'pending') return 
			this.data = data
			this.state = 'rejected'
		}
		excutor(resolve,reject)
	}
}

```

写完上面的代码后，可以小小地进行一下测试，这里使用了5条测试用例

```javascript
// 测试同步，测试用例1
let p = new self_promise((resolve,reject)=>{
	// 1.同步+resolve
	resolve('data') 
})

// 测试同步，测试用例2
let p = new self_promise((resolve,reject)=>{
	// 2.同步+reject
	reject('抛出错误') 
})

// 测试同步，测试用例3
let p = new self_promise((resolve,reject)=>{
	// 2.同步+resolve和reject
	resolve('data')
	reject('抛出错误') 
})

// 测试异步，测试用例4
let p = new self_promise((resolve,reject)=>{
	setTimeout(()=>{
	  let res = {code:200,msg:"测试信息",data:'异步的数据'}
	  if(res.code === 200){
		resolve(res.data)
	  }else{
		reject(res.msg)
	  }
	},2000)
})

// 测试异步，测试用例5
let p = new self_promise((resolve,reject)=>{
	setTimeout(()=>{
	  let res = {code:500,msg:"测试信息",data:'异步的数据'}
	  if(res.code === 200){
		resolve(res.data)
	  }else{
		reject(res.msg)
	  }
	},2000)
})
```

经过测试，以上用例均符合预期，下面继续写

## 第三步：完善配套的Promise.prototype.then和Promise.prototype.catch方法

```javascript
// 第三步，完善配套的Promise.prototype.then和Promise.prototype.catch方法
class self_promise {
	constructor(excutor){
		// const self = this  // 保存this，因为作为参数的回调函数调用后this会指向window；也可以使用箭头函数去避免这个问题。
		this.data = null;
		this.state = 'pending'
		const resolve = (data)=>{
			if(this.state !== 'pending') return 
			this.data = data
			this.state = 'fulfilled'
		}
		const reject = (data)=>{
			if(this.state !== 'pending') return 
			this.data = data
			this.state = 'rejected'
		}
		excutor(resolve,reject)
	}
	/** 思路如下：
	  1.then函数接受2个回调函数作为参数，返回一个新的promise
	  2.then函数内部需要判断当前Promise实例状态，决定是执行第一个参数的函数还是第二个参数的函数
	  3.返回值是一个新的Promise实例，这里我们需要根据onResolve和onReject和返回值和执行情况判断then返回的Promise实例：
		1）如果参数的回调函数内部（onResolve，onReject）执行报错，则调用reject，这里我们需要使用try..catch去捕获
		2）如果是一个Promise实例，则直接返回这个实例，否则将返回值作为参数调用resolve
	*/
	then(onResolve,onReject){
		let result;
		try{
		  if(this.state === "fulfilled" && onResolve && typeof onResolve === 'function'){
		    result = onResolve(this.data)
		  }
		  if(this.state === "rejected" && onReject && typeof onReject === 'function'){
		    result = onReject(this.data)
		  }
		}catch(err){
			return new self_promise((resolve,reject)=>{
				reject(err)  
			}) 
		}

		if(result && result instanceof self_promise){
			return result
		}else{
			return new self_promise((resolve,reject)=>{
				resolve(result)  
			})
		}

	}
	// 基于已经写好的then()方法去实现
	catch(onReject){
		self_promise.prototype.then(undefined,onReject)
	}
}
```

按照想法写好了，下面进入测试

```javascript
// 测试同步，测试用例1
let p = new self_promise((resolve,reject)=>{
	// 1.同步+resolve
	resolve('data') 
})


p.then((data)=>{
    return data
},(reason)=>{
    return reason
})


// 测试同步，测试用例2
let p = new self_promise((resolve,reject)=>{
	// 2.同步+reject
	reject('抛出错误') 
})

p.then((data)=>{
    return data
},(reason)=>{
    return reason
})

// 测试同步，测试用例3
let p = new self_promise((resolve,reject)=>{
	// 同步+resolve
	resolve('data')  
})

p.then((data)=>{
    return new self_promise((resolve,reject)=>{ reject(1) })
},(reason)=>{
    return reason
})

// 测试异步，测试用例4
let p = new self_promise((resolve,reject)=>{
	setTimeout(()=>{
	  let res = {code:200,msg:"测试信息",data:'异步的数据'}
	  if(res.code === 200){
		resolve(res.data)
	  }else{
		reject(res.msg)
	  }
	},2000)
})

p.then((data)=>{
    return data
},(reason)=>{
    return reason
})

// 测试异步，测试用例5
let p = new self_promise((resolve,reject)=>{
	setTimeout(()=>{
	  let res = {code:500,msg:"测试信息",data:'异步的数据'}
	  if(res.code === 200){
		resolve(res.data)
	  }else{
		reject(res.msg)
	  }
	},2000)
})

p.then((data)=>{
    return data
},(reason)=>{
    return reason
})

```

经过测试，发现在异步的时候会有问题。分析了一下，原因是then里面的代码是同步执行的，当执行then的代码的时候，异步的操作没有进行完，状态和数据没有发生改变，因此then返回的promise里面的data会有问题
想要解决这个问题，就必须在异步操作之后再进行then的操作，比如在promise实例上维护一个事件队列，在then的时候将回调事件函数加入该队列，异步执行的时候去执行维护的队列里面的事件

这样就解决了执行回调函数的问题。但是，这同时也带来了另外一个问题，返回值的问题怎么办呢？
怎么拿到返回值
怎么捕获异常呢

这里我没思路，于是参考了一下别人的实现，发现别人是这样做的
1.在then直接返回一个promise的实例，利用resolve和reject去配合异步修改实例状态和数据
2.在内部包一层函数，将回调函数放到该函数去执行，解决了上面拿返回值和捕获异常的问题

决定采用，实现如下：

```javascript
// 第三步，完善配套的Promise.prototype.then和Promise.prototype.catch方法
class self_promise {
	constructor(excutor){
		// const self = this  // 保存this，因为作为参数的回调函数调用后this会指向window；也可以使用箭头函数去避免这个问题。
		this.data = null;
		this.state = 'pending'
		this.queue = {onResolveQueue:[],onRejectQueue:[]}
		const resolve = (data)=>{
			if(this.state !== 'pending') return 
			this.data = data
			this.state = 'fulfilled'
			this.queue.onResolveQueue.forEach((item)=>{
				item()
			})
		}
		const reject = (data)=>{
			if(this.state !== 'pending') return  
			this.data = data
			this.state = 'rejected'
			this.queue.onRejectQueue.forEach((item)=>{
				item()
			})
		}
		excutor(resolve,reject)
	}
	/** 思路如下：
	  1.then函数接受2个回调函数作为参数，返回一个新的promise
	  2.then函数内部需要判断当前Promise实例状态，决定是执行第一个参数的函数还是第二个参数的函数
	  3.返回值是一个新的Promise实例，这里我们需要根据onResolve和onReject和返回值和执行情况判断then返回的Promise实例：
		1）如果参数的回调函数内部（onResolve，onReject）执行报错，则调用reject，这里我们需要使用try..catch去捕获
		2）如果是一个Promise实例，则直接返回这个实例，否则将返回值作为参数调用resolve
	*/
	then(onResolve,onReject){
		let result;
		return new self_promise((resolve,reject)=>{
			if(onResolve && typeof onResolve === 'function'){
				this.queue.onResolveQueue.push(()=>{
					try{
						result = onResolve(this.data)
						if(result && result instanceof self_promise){
							resolve(result.data)
						}else{
							resolve(result)
						}
					}catch(err){
						reject(err)
					}
				})
			}
			if(onReject && typeof onReject=== 'function'){
				this.queue.onRejectQueue.push(()=>{
					try{
						result = onReject(this.data)
						if(result && result instanceof self_promise){
							resolve(result.data)
						}else{
							resolve(result)
						}
					}catch(err){
						reject(err)
					}
				})
			}
		})
	}
	// 基于已经写好的then()方法去实现
	catch(onReject){
		self_promise.prototype.then(undefined,onReject)
	}
}

```

重新拿异步的测试用例进行测试

```javascript
// 测试异步，测试用例4
let p = new self_promise((resolve,reject)=>{
	setTimeout(()=>{
	  let res = {code:200,msg:"测试信息",data:'异步的数据'}
	  if(res.code === 200){
		resolve(res.data)
	  }else{
		reject(res.msg)
	  }
	},2000)
})

p.then((data)=>{
    return data
},(reason)=>{
    return reason
})

// 测试异步，测试用例5
let p = new self_promise((resolve,reject)=>{
	setTimeout(()=>{
	  let res = {code:500,msg:"测试信息",data:'异步的数据'}
	  if(res.code === 200){
		resolve(res.data)
	  }else{
		reject(res.msg)
	  }
	},2000)
})

p.then((data)=>{
    return data
},(reason)=>{
    return reason
})

// 测试异步，测试用例6
let p = new self_promise((resolve,reject)=>{
	setTimeout(()=>{
	  let res = {code:200,msg:"测试信息",data:'异步的数据'}
	  if(res.code === 200){
		resolve(res.data)
	  }else{
		reject(res.msg)
	  }
	},2000)
})

p.then((data)=>{
    return new self_promise((resolve,reject)=>{resolve('test')})
},(reason)=>{
    return new self_promise((resolve,reject)=>{reject('fail')})
})
```

经过测试，发现异步的数据符合预期，好了，这下解决了异步的问题了

修改完代码，按道理我们也要重新测试一下跑成功的用例，因此我们再来测试一下之前同步的用例1，2，3

```javascript
// 测试同步，测试用例1
let p = new self_promise((resolve,reject)=>{
	// 1.同步+resolve
	resolve('data') 
})


p.then((data)=>{
    return data
},(reason)=>{
    return reason
})


// 测试同步，测试用例2
let p = new self_promise((resolve,reject)=>{
	// 2.同步+reject
	reject('抛出错误') 
})

p.then((data)=>{
    return data
},(reason)=>{
    return reason
})

// 测试同步，测试用例3
let p = new self_promise((resolve,reject)=>{
	// 同步+resolve
	resolve('data')  
})

p.then((data)=>{
    return new self_promise((resolve,reject)=>{ reject(1) })
},(reason)=>{
    return reason
})
```

测试完后，我们发现，代码在同步的用例中失效了

分析后发现：同步的时候，执行队列的函数的时候是空的，因为此时then还没有执行，没有事件函数传递进队列

这里的解决方案是，再then函数中判断state的值，pending说明是异步到达，其他说明是同步到达

```javascript

// 第三步，完善配套的Promise.prototype.then和Promise.prototype.catch方法
class self_promise {
	constructor(excutor){
		// const self = this  // 保存this，因为作为参数的回调函数调用后this会指向window；也可以使用箭头函数去避免这个问题。
		this.data = null;
		this.state = 'pending'
		this.queue = {onResolveQueue:[],onRejectQueue:[]}
		const resolve = (data)=>{
			if(this.state !== 'pending') return 
			this.data = data
			this.state = 'fulfilled'
			this.queue.onResolveQueue.forEach((item)=>{
				item()
			})
		}
		const reject = (data)=>{
			if(this.state !== 'pending') return  
			this.data = data
			this.state = 'rejected'
			this.queue.onRejectQueue.forEach((item)=>{
				item()
			})
		}
		excutor(resolve,reject)
	}
	/** 思路如下：
	  1.then函数接受2个回调函数作为参数，返回一个新的promise
	  2.then函数内部需要判断当前Promise实例状态，决定是执行第一个参数的函数还是第二个参数的函数
	  3.返回值是一个新的Promise实例，这里我们需要根据onResolve和onReject和返回值和执行情况判断then返回的Promise实例：
		1）如果参数的回调函数内部（onResolve，onReject）执行报错，则调用reject，这里我们需要使用try..catch去捕获
		2）如果是一个Promise实例，则直接返回这个实例，否则将返回值作为参数调用resolve
	*/
	then(onResolve,onReject){
		let that = this
		let result;
		return new self_promise((resolve,reject)=>{
			console.log('that.state',that.state)
			if(that.state === 'pending'){
			  if(onResolve && typeof onResolve === 'function'){
				this.queue.onResolveQueue.push(()=>{
					try{
						result = onResolve(that.data)
						if(result && result instanceof self_promise){
							resolve(result.data)
						}else{
							resolve(result)
						}
					}catch(err){
						reject(err)
					}
				})
			  }
			  if(onReject && typeof onReject=== 'function'){
				this.queue.onRejectQueue.push(()=>{
					try{
						result = onReject(that.data)
						if(result && result instanceof self_promise){
							resolve(result.data)
						}else{
							resolve(result)
						}
					}catch(err){
						reject(err)
					}
				})
			  }
			}else{
				if(onResolve && typeof onResolve === 'function' && that.state === 'fulfilled'){
					try{
						result = onResolve(this.data)
						if(result && result instanceof self_promise){
							resolve(result.data)
						}else{
							resolve(result)
						}
					}catch(err){
						reject(err)
					}
				}
				if(onReject && typeof onReject === 'function' && that.state === 'rejected'){
					try{
						result = onReject(this.data)
						if(result && result instanceof self_promise){
							resolve(result.data)
						}else{
							resolve(result)
						}
					}catch(err){
						reject(err)
					}
				}
			}

		})
	}
	// 基于已经写好的then()方法去实现
	catch(onReject){
		self_promise.prototype.then(undefined,onReject)
	}
}


```

写完后，再次使用同步的用例去测试发现，已经可以全部通过

把重复的代码封装一下

```javascript

class self_promise {
	constructor(excutor){
		// const self = this  // 保存this，因为作为参数的回调函数调用后this会指向window；也可以使用箭头函数去避免这个问题。
		this.data = null;
		this.state = 'pending'
		this.queue = {onResolveQueue:[],onRejectQueue:[]}
		const resolve = (data)=>{
			if(this.state !== 'pending') return 
			this.data = data
			this.state = 'fulfilled'
			this.queue.onResolveQueue.forEach((item)=>{
				item()
			})
		}
		const reject = (data)=>{
			if(this.state !== 'pending') return  
			this.data = data
			this.state = 'rejected'
			this.queue.onRejectQueue.forEach((item)=>{
				item()
			})
		}
		excutor(resolve,reject)
	}
	then(onResolve,onReject){
		let that = this
		let result;
		return new self_promise((resolve,reject)=>{
			function handle(callback,state,type){
				if(callback && typeof callback === 'function'){
				  let func = ()=>{
					try{
						result = callback(that.data)
						if(result && result instanceof self_promise){
							resolve(result.data)
						}else{
							resolve(result)
						}
					}catch(err){
						reject(err)
					}
				}
				if(type === 'pending'){
					type === 'onResolve' ? this.queue.onResolveQueue.push(func) : this.queue.onRejectQueue.push(func)
				}else{
					func()
				}


			  }
			}
			if(that.state === 'pending'){
				handle(onResolve,'pending','onResolve')
				handle(onReject,'pending','onReject')
			}else{
				if(that.state === 'fulfilled'){
					handle(onResolve,'fullfilled')
				}
				if(that.state === 'rejected'){
					handle(onReject,'fullfilled')
				}
			}

		})
	}
	// 基于已经写好的then()方法去实现
	catch(onReject){
		self_promise.prototype.then(undefined,onReject)
	}
}



```

## 第四步：考虑宏任务微任务

最后，其实我们还要考虑一个【宏任务和微任务】的问题
